### ISSUE TITLE
XML Tabellen werden nicht korrekt geparst

### ISSUE THREAD

**Issue by juliankeppler** [TUBAF-IfI-LiaScript/VL_EingebetteteSysteme#26]
Tabellen werden nicht als Tabellen gerendert. Stadtdessen werden die unverarbeiteten XML-Tags abgebildet.

[Beispiel](https://liascript.github.io/course/?https://raw.githubusercontent.com/TUBAF-IfI-LiaScript/VL_EingebetteteSysteme/master/03_Minimierung.md#5):
![image](https://user-images.githubusercontent.com/73278698/101506286-7e6d9600-3975-11eb-9f90-d865e17dd682.png)

**Comment by SebastianZug** [comment]
Hallo Herr Keppler,

ich finde das Beispiel auf die schnelle nicht. Können Sie mir sagen, um welches Dokument es sich handelt?

Welchen Browser benutzen Sie?

Grüße

Sebastian Zug

**Comment by juliankeppler** [comment]
Hallo Professor Zug,

Ich benutze Google Chrome (habe es auch mit Firefox probiert, selbes Problem). Der Fehler tritt bei mir an mehreren Stellen in den Materialien der 3. Vorlesung (Minimierung) auf. Zum Beispiel auf der 1. und der 4. Folie bei den Karnaugh-Veitch-Diagrammen: [https://liascript.github.io/course/?https://raw.githubusercontent.com/TUBAF-IfI-LiaScript/VL_EingebetteteSysteme/master/03_Minimierung.md#5](https://liascript.github.io/course/?https://raw.githubusercontent.com/TUBAF-IfI-LiaScript/VL_EingebetteteSysteme/master/03_Minimierung.md#5).

VG

Julian Keppler

**Comment by SebastianZug** [comment]
Ok, da gab es mit der neuen Version des Parsers von LiaScript ein Problem. Ist jetzt wieder gerichtet. Können Sie es noch mal prüfen?

**Comment by juliankeppler** [comment]
Tabellen funktionieren wieder. Vielen Dank.
